### ISSUE TITLE
AttributeError when server closes socket

### ISSUE THREAD

**Issue by jimfunk** [mardiros/aioxmlrpc#8]
If the XMLRPC server closes the socket, which is rather common if it's Apache, I get this error:

```
Traceback (most recent call last):
  File "/usr/share/routest/env/lib/python3.5/site-packages/aioxmlrpc/client.py", line 71, in request
    connector=self._connector, loop=self._loop)
  File "/usr/share/routest/env/lib/python3.5/site-packages/aiohttp/client.py", line 605, in __iter__
    return (yield from self._coro)
  File "/usr/share/routest/env/lib/python3.5/site-packages/aiohttp/client.py", line 161, in _request
    raise RuntimeError('Session is closed')
RuntimeError: Session is closed
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/usr/share/routest/env/lib/python3.5/site-packages/routest/resource/space/serializers.py", line 159, in check_job_status
    self.job_status = await self.lava.scheduler.job_status(self.job_id)
  File "/usr/share/routest/env/lib/python3.5/site-packages/aioxmlrpc/client.py", line 37, in __call__
    ret = yield from self.__send(self.__name, args)
  File "/usr/share/routest/env/lib/python3.5/site-packages/aioxmlrpc/client.py", line 130, in __request
    verbose=self.__verbose
  File "/usr/share/routest/env/lib/python3.5/site-packages/aioxmlrpc/client.py", line 80, in request
    raise ProtocolError(url, response.status,
AttributeError: 'NoneType' object has no attribute 'status'
```

**Comment by rutsky** [comment]
@jimfunk I fixed this error in #10, please take a look.
